### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ericsaboia** [imsnif/synp#13]
I'm getting this error at [npmToYarnResolved](https://github.com/imsnif/synp/blob/master/lib/entry.js#L21-L27) because the `integrity` of the package `ua-parser-js` comes undefined.

The package is a dependency of a top-level dependency in my project. 

Here's the `package-json.lock` snippet:

```
"amplitude-js": {
      "version": "3.7.0",
      "resolved": "https://registry.npmjs.org/amplitude-js/-/amplitude-js-3.7.0.tgz",
      "integrity": "sha512-8wvzyM0c6RV5MAsWxkB/C1CMthSIGE+SZE1a5yc5MBzHb7hUkb/d6e7YaadkddicjicMpbFkGziA1e6TBvqC1A==",
      "requires": {
        "@segment/top-domain": "https://registry.npmjs.org/@segment/top-domain/-/top-domain-3.0.0.tgz",
        "blueimp-md5": "https://registry.npmjs.org/blueimp-md5/-/blueimp-md5-2.10.0.tgz",
        "json3": "https://registry.npmjs.org/json3/-/json3-3.3.2.tgz",
        "lodash": "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz",
        "ua-parser-js": "github:amplitude/ua-parser-js#ed538f16f5c6ecd8357da989b617d4f156dcf35d"
      },
      "dependencies": {
        "ua-parser-js": {
          "version": "github:amplitude/ua-parser-js#ed538f16f5c6ecd8357da989b617d4f156dcf35d"
        }
      }
    },
```

**Comment by imsnif** [comment]
Hey @ericsaboia - thanks for opening the issue! This is actually a result of https://github.com/imsnif/synp/issues/12
I still have not gotten around to fixing it (I first want to support sha512 once `yarn` supports it).

For now, I think the workaround here should help you out:
https://github.com/imsnif/synp/issues/6
