### ISSUE TITLE
Problem with converting from Yarn to NPM: dependencies@undefined

### ISSUE THREAD

**Issue by agarbund** [imsnif/synp#17]
Steps to reproduce with attached files:

```
yarn
synp --source-file yarn.lock
rm -rf node_modules
npm i
```

Getting error:
```
No matching version found for dependencies@undefined
```

Using Yarn 0.27.5 and npm 5.6.0

#### Are you reporting a conversion error? Please include a link to `yarn.lock` / `package-lock.json`:
[yarn.lock.txt](https://github.com/imsnif/synp/files/2105576/yarn.lock.txt)
#### Are you reporting a conversion error? Please also include a link to your `package.json`:
[package.json.txt](https://github.com/imsnif/synp/files/2105571/package.json.txt)

**Comment by agarbund** [comment]
Note: after upgrading to Yarn 1.7.0 and repeating the whole procedure, error during `npm i` has changed too:
```
Cannot read property 'match' of undefined
```

**Comment by imsnif** [comment]
Hey @agarbund - first, sorry for taking so long to get to this issue. I just checked this manually and for me it works with npm `6.1.0`
Can you try upgrading and seeing if it does the trick?

If not, it might have to do with `fsevents` which is an optional dependency not installed on my platform (linux). If that is the case, I might ask for your help debugging this as I do not have access to a box with a supported OS.

Anyway, please let me know - thanks for reporting this!

**Comment by agarbund** [comment]
Hey @imsnif you were right, problem was with `fsevents` package. I removed all packages connected to it with Yarn, converted successfully to npm, and then installed them again with npm.

Thanks for your support and for the great tool!

**Comment by elado** [comment]
Also got `Cannot read property 'match' of undefined`

Debugged, and saw that in npm it was failing because package-lock.json had a root `dependencies` node at the end of the file. Deleted the node and it worked.
