### ISSUE TITLE
add support for pnpm

### ISSUE THREAD

**Issue by DanielRuf** [imsnif/synp#18]
#### Issue description:

@pnpm is another package manager which solves many issues of yarn and npm. pnpm uses a shrinkwrap.yaml lockfile similar to the shrinkwrap file of npm but uses another approach when installing dependencies.

**Comment by imsnif** [comment]
Hey @DanielRuf - this was actually "in the cards" for a while but I didn't know how feasible it would be considering pnpm's heavy manipulation of the physical tree. I think it's worth some investigation. Would you be interested in offering a design/implementation?

**Comment by DanielRuf** [comment]
I can probably invest some time in the next weeks (currently not much time this week). @zkochan might have the needed information so we can plan the needed steps to get to the desired result.

**Comment by imsnif** [comment]
I'd be happy to help in any way I can. The lib will probably need some work on generic logical/physical tree structures to facilitate 3-way conversions. We might even get some nice libs out of it, been in my head for a while now.

**Comment by DanielRuf** [comment]
Sounds great =)
