### ISSUE TITLE
Cannot read property forEach of undefined

### ISSUE THREAD

**Issue by chrismwendt** [imsnif/synp#19]
Conversion fails on https://github.com/sourcegraph/browser-extensions/blob/37ae8206a9ec7496bfedbb5fe8a484e73ae34eb9/package-lock.json with `synp -s package-lock.json`

The error occurs in the source code here https://sourcegraph.com/github.com/imsnif/synp/-/blob/util/format.js#L64:17

**Comment by imsnif** [comment]
Hey @chrismwendt - this actually works for me.

##### What I did:
```
git clone https://github.com/sourcegraph/browser-extensions.git
cd browser-extensions
npm install
synp --source-file package-lock.json
```

Maybe `node_modules` weren't installed?

Let me know if this works for you.

**Comment by chrismwendt** [comment]
Hmm, that didn't work for me. Here's the output:

```
[I] ~ git clone https://github.com/sourcegraph/browser-extensions.git
      cd browser-extensions
      npm install
      synp --source-file package-lock.json
Cloning into 'browser-extensions'...
remote: Counting objects: 1748, done.
remote: Total 1748 (delta 0), reused 0 (delta 0), pack-reused 1747
Receiving objects: 100% (1748/1748), 1.38 MiB | 278.00 KiB/s, done.
Resolving deltas: 100% (1182/1182), done.

...

added 2434 packages from 2031 contributors and audited 24574 packages in 229.023s
found 89 vulnerabilities (7 low, 74 moderate, 7 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Cannot read property 'forEach' of undefined

  Usage: synp [options]

  Options:

    -V, --version                    output the version number
    -s, --source-file [source-file]  The path to the yarn.lock or package-lock.json to be converted
    -h, --help                       output usage information

[I] 2 ~/browser-extensions [master] synp --version
1.3.0
[I] ~/browser-extensions [master]
```

**Comment by chrismwendt** [comment]
What's your `npm --version`? I'm on 6.4.0

**Comment by imsnif** [comment]
I was on 6.3.0, tried with 6.4.1 and it still works for me.
I'm guessing (I've seen this before) that this has to do with platform dependent dependencies (eg. `fsevents`). In order to debug this, would you be willing to try something?
Try removing all lines in `package-lock.json` containing 'fsevents' (I think there are ~5) and then converting?

**Comment by chrismwendt** [comment]
That didn't work either 😦 I removed 2 lines like `"fsevents": ...` and the whole `"fsevents": {` property.

**Comment by imsnif** [comment]
This is quite strange. Has the `package-lock.json` been manually edited in the past? I see some entries with `"resolved": false` - I don't know if these are valid (haven't seen them before).

**Comment by chrismwendt** [comment]
I doubt it's been manually edited, but I suppose it's possible. Any insight into why the `forEach` error is occurring? I'm curious what the code is attempting to do when it hits that error.

**Comment by imsnif** [comment]
Basically, it means there's an inconsistency between the `package-lock.json` and the installed `node_modules` which `synp` cannot reconcile (it has facilities for dealing with optional dependencies, but they're a little buggy sometimes).
If you're converting to `yarn.lock`, could you maybe try to use `yarn` itself for the conversion? `yarn import` should do the trick for you (the support was added after this tool had been around for a while). Let me know if it worked out?
I'm curious to solve this, but don't want to keep you hanging.
