### ISSUE TITLE
Finding issues

### ISSUE THREAD

**Issue by hermanbanken** [imsnif/synp#23]
#### Issue description:
npm i: match of undefined

Issues like these are sometimes caused by package-lock.json missing some `version` fields.
You can quickly discover those via:

```javascript
function check(o, k) {
  typeof o.version === "undefined" && console.log(`${k} has no version`);
  o.dependencies && Object.keys(o.dependencies).forEach(k => check(o.dependencies[k], k));
}
check(require("./package-lock"))
```

which you can also run inline like this:

```bash
node --eval 'function check(o, k) { typeof o.version === "undefined" && console.log(k + " has no version"); o.dependencies && Object.keys(o.dependencies).forEach(k => check(o.dependencies[k], k)); }; check(require("./package-lock"));'
```

**Comment by imsnif** [comment]
Hey @hermanbanken - could you give me more information about the error you're describing? Preferably some way to recreate it with a `package.json` and a `package-lock.json`. I think it'll help me understand what you mean.

**Comment by hermanbanken** [comment]
See issue #17, it is the same.

**Comment by imsnif** [comment]
Yeah, I agree error reporting and lockfile validation in `synp` are a little bad. I think I'd like to see a more 'whole' solution that would catch (or could be extended to catch) all possible errors and even explain them. For example, why do these certain packages have no version? What can the user do about it?

Thanks for the suggestion though! If you feel like working on something in a PR (or discussing it first in an 'validation and error reporting' issue) that would be great.

**Comment by hermanbanken** [comment]
I mainly wanted to post the quick check that people can run to continue. I was just hoping to hint people into finding solutions to similar problems like mine.

I'm in the process of updating 20+ repositories back to npm. I don't have the time to philosophize about how to improve synp, I just need a fix that works _now_. Sorry!

**Comment by imsnif** [comment]
No worries, I just don't want to keep issues open without having the ability to do something about them. :)
Happy converting!
