### ISSUE TITLE
Add --force option that will delete an existing lockfile if it exists

### ISSUE THREAD

**Issue by shinriyo** [imsnif/synp#26]
#### Issue description:

```
synp --source-file package-lock.json
destination file yarn.lock already exists, will not overwrite
```

I hope `--forcely -f` option.

**Comment by imsnif** [comment]
Thanks @shinriyo - sounds like a good feature. Want to send a PR?

**Comment by shinriyo** [comment]
@imsnif Thank you.
No, I don't. I am going to wait.

**Comment by imsnif** [comment]
This was fixed by @harryparkdotio, thanks again!
