### ISSUE TITLE
Could not find parent dir!

### ISSUE THREAD

**Issue by LuudJanssen** [imsnif/synp#46]
#### Issue description:

Bet you didn't expect to get an issue report 10 minutes after releasing a new version, but the new release seems to break something in my workflow. I get the following error: `Could not find parent dir!`, while everything worked fine one hour ago.

#### Are you reporting a conversion error? Please include a link to `yarn.lock` / `package-lock.json`:

[lockfiles.zip](https://github.com/imsnif/synp/files/5095555/lockfiles.zip)

#### Are you reporting a conversion error? Please also include a link to your `package.json`:

See attached *.zip

EDIT: FYI I ran `npx synp --source-file yarn.lock`

**Comment by imsnif** [comment]
Oi, sorry about that! @antongolub, feel like taking a look? If you don't have time, let me know and I'll delve into your changes and see what's up. @LuudJanssen, for now working with `1.7` works for you?

**Comment by LuudJanssen** [comment]
No problem @imsnif! Yes, running `npx synp@1.7.0 --source-file yarn.lock` works for me.

**Comment by antongolub** [comment]
Hi there, 
@imsnif @LuudJanssen

I'll look for what could break. Sorry for the inconvenience.

**Comment by antongolub** [comment]
@imsnif,

Could you verify #47 fix and release a patch?

**Comment by antongolub** [comment]
@LuudJanssen, @alexiusp ,
Any news? 

The latest beta build is available as [@antongolub/synp](https://www.npmjs.com/package/@antongolub/synp) package. If everything works fine, we would like to release the pull request and close the issue.

**Comment by alexiusp** [comment]
I have tried version 1.8.1. Issue mentioned above has gone, but I have another issue. Seems like this version of synp works incorrectly with private repositories and/or with dependencies referenced by direct github link instead of npm package name. When I run synp v.1.8.1 with one of my repos I see this:

> 
> synp --source-file yarn.lock --force
> Invalid URL: git+ssh://git@github.com:****/***_components.git#0b2e***637d
> Usage: synp [options]
> 
> Options:
>   -V, --version                    output the version number
>   -s, --source-file [source-file]  The path to the yarn.lock or
>                                    package-lock.json to be converted
>   -f, --force                      Force overwrite destination file
>   --with-workspace                 Enable experimental npm lockfile v2
>                                    processing
>   -h, --help                       display help for command
> 

In my package.json I have a dependency like this:

>    "***_components": "git+ssh://git@github.com:***/***_components.git"

It's a private repository. Build process on Jenkins is set up correctly and all necessary files are in node_modules. Yarn also understands this kind of dependencies and install them properly.

**Comment by antongolub** [comment]
@alexiusp
I see... I've replaced deprecated `url.parse(val)` call with `new url.URL(val)`.

**Comment by antongolub** [comment]
@alexiusp

Could you try the latest beta? `npx @antongolub/synp@2.0.20`

**Comment by imsnif** [comment]
Hey @antongolub - let's go forward with your fixes. I think if it doesn't fix stuff for @alexiusp we can re-examine it. Is everything merged, can I bump the version and publish?

**Comment by antongolub** [comment]
Yep. Let’s do it.

-
Anton Golub

**Comment by imsnif** [comment]
@antongolub - the last commit on master is `1.8.1`

**Comment by antongolub** [comment]
@imsnif 
AFK. Could you merge the latest PR?

**Comment by antongolub** [comment]
@alexiusp, @LuudJanssen,

Everything should be fixed in v1.8.2. If not, feel free to open another one issue.

**Comment by alexiusp** [comment]
Sorry for losing the track. In version 1.8.2 everything works as expected. Thank you!
