### ISSUE TITLE
Conversion from package-lock.json fails

### ISSUE THREAD

**Issue by joshuanapoli** [imsnif/synp#6]
When I run `synp --source-file package-lock.json` with this file https://www.dropbox.com/s/9w4xpxmigo4rbiq/package-lock.json?dl=0 I see "Cannot read property 'replace' of undefined. Any idea how I can work around this problem?

I have synp version 1.0.3.

**Comment by imsnif** [comment]
Hey @joshuanapoli - is your `node_modules` directory current and installed by npm?
If you:
1. remove `node_modules` completely
2. `npm install`
3. `synp --source-file package-lock.json`

Does it still happen? If it does and you can link to the repo (or even just add the `package.json`) file to the `package-lock.json` file you linked, I'd be happy to take a look!

**Comment by skeggse** [comment]
Ah, looks like this is a manifestation of #9 - I see this entry in the given `package-lock.json`:

```json
"formulajs": {
  "version": "github:handsontable/formula.js#aa9d4acc54e4e0959b70dd0f8c6019774d57498d",
  "requires": {
    "bessel": "0.2.0",
    "jStat": "1.7.1",
    "numbro": "1.11.0"
  }
}
```

**Comment by imsnif** [comment]
Nice catch @skeggse! The funny thing is, that for me this does not fail the `synp` conversion. Even before your fix. I just end up getting the target-file with a malformed (`sha1-`) sri. I'm guessing this results from platform differences in the Buffer module (I'm on a linux box).

In any case: @joshuanapoli - if this still happens for you, you can work around it by:
1. Manually removing all `github` entries in `package-lock.json`
2. Running the conversion (`synp --source-file package-lock.json`)
3. Running `yarn` - which should add these again*

This is a somewhat ugly workaround, I apologize. I opened an issue for this: #12 and hope to address it soon!

* Careful though, for this one time you will not have the benefit of integrity checks
