### ISSUE TITLE
Support yarn integrity field

### ISSUE THREAD

**Issue by imsnif** [imsnif/synp#7]
Once this is closed: https://github.com/yarnpkg/yarn/issues/816

**Comment by DeTeam** [comment]
Even though issue is not closed, the PR is. Seem like this can be worked on (:

**Comment by imsnif** [comment]
@DeTeam - yes, that's right! Important to note that the support here should be added rather than replaced. I'd like to maintain backwards compatibility to (converting from) yarn lockfiles that do not have an `integrity` field.

If you feel like having a go at this, your PRs are always welcome. :)
