### ISSUE TITLE
Unsuccesfull convertion from yarn to package locks

### ISSUE THREAD

**Issue by talamaska** [imsnif/synp#8]
I have an error in the console: Unknown token 3:1 in lockfile

**Comment by imsnif** [comment]
Hey @talamaska - could you paste a link to your `yarn.lock` and the `package.json` of the package you're converting? I'd be happy to take a look!

**Comment by talamaska** [comment]
https://gist.github.com/talamaska/e7c9f8dbdc9c0153efdfe2c16831c397

**Comment by imsnif** [comment]
Thanks @talamaska - could you please also post your `package.json`?

**Comment by talamaska** [comment]
sure
https://gist.github.com/talamaska/d824b2393e04718bc6f28be6ce352e58

**Comment by imsnif** [comment]
Hey @talamaska - for me it worked. What I did:
1. `mkdir admin`
2. `wget https://gist.githubusercontent.com/talamaska/e7c9f8dbdc9c0153efdfe2c16831c397/raw/ed242bce606859ccbbd668f0ef70ca77d988562f/yarn.lock`
3. https://gist.githubusercontent.com/talamaska/d824b2393e04718bc6f28be6ce352e58/raw/b5b15b63700079b5f7de4a3446944ab4ae70e514/package.json
4. `yarn`
5. `synp --source-file yarn.lock`

If you perform the same steps, does it still happen?

**Comment by talamaska** [comment]
I don't have wget in power shell or in gitbash, I used the linux subsystem bash for wget, installed with yarn outside of bash and run the step 6. No issues. This is weird.

**Comment by talamaska** [comment]
went to my real project, deleted my node_modules. installed with yarn again, step 6 have the same error.

**Comment by talamaska** [comment]
ok, so I compared the files. The only difference is the line endings. If they are linux like 'LF' - your script works fine, but if windows style - CRLF it doesn't. I think you should account for the OS specific line endings. Just like when using paths windows and linux style e.g. '/' or '\'

**Comment by imsnif** [comment]
@talamaska - I was beginning to suspect as much! `synp` uses yarn's own parser, and for some reason I took it for granted that it can handle both. In any case, I issued a fix for this. `1.2.0` should solve this. If you're still having issues, please let me know!

**Comment by talamaska** [comment]
It doesn't fix it, same error. Because you have used eol.auto which changes the eol to the current OS. Now if I'm on windows , my eol is clrf, and basically this won't change anything to my yarn.lock.
I think you should convert with eol.lf(text) instead of auto, since on windows with files that have linux line endings running your script was successfull, but with windows eol it is not. normaly git make the changes on push and checkout, in order to not break eol for everyone. It checkouts as windows and commits as linux.

**Comment by imsnif** [comment]
My apologies! You are of course correct. :)
How about now? With `1.2.1`?

**Comment by talamaska** [comment]
works now, thanks
