### ISSUE TITLE
Terminal Broken after initial conversion.

### ISSUE THREAD

**Issue by Ramon404** [imsnif/synp#90]
#### Issue description:
After initially trying out the command to convert yarn.lock to package-lock.json I got those weird infinite loop of symbols on my terminal. That kept on for hours before I force stopped it. It keeps happening when I try and run other npm commands like npm run start, even after uninstalling the synp package. Please see the screenshot attached.
`
![Screenshot 2022-01-10 160118](https://user-images.githubusercontent.com/61785879/148778722-4c805266-54e4-4613-a3de-18c42e6dadd9.png)
`

**Comment by antongolub** [comment]
Hey, @Ramon404,

Have you tried v1.9.9?

**Comment by antongolub** [comment]
We've already pinned `colors` to v1.4.0 and release the fix as a part of v1.9.9
https://github.com/imsnif/synp/blob/master/package.json#L39

**Comment by antongolub** [comment]
Seems we have to deprecate all synp versions of range `<1.9.9`.

**Comment by Ramon404** [comment]
Hey. Sorry I've actually just uninstalled it because I had to continue with my work. I'll check later what version I had (I just installed the latest from npm), and see if v1.9.9 fixes the issue

**Comment by antongolub** [comment]
Everything is fine now. The issue has gone as a result of the removal of compromised `colors`  versions from the npm registry.
